version: '3.1'
services:
  adminer:
    image: adminer
    container_name: adminer-worktransfer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
  database:
    image: postgres
    container_name: postgres-worktransfer
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}